//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semester_3_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int ad_Id { get; set; }
        public string ad_name { get; set; }
        public string ad_pass { get; set; }
    }
}
