//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semester_3_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public int Id { get; set; }
        public string Fullname { get; set; }
        public string Email { get; set; }
        public int PhoneNo { get; set; }
        public string CV { get; set; }
        public string Password { get; set; }
        public string Username { get; set; }
        public string Score { get; set; }
    }
}
