//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semester_3_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetTest
    {
        public int examId { get; set; }
        public System.DateTime exam_date { get; set; }
        public int fk_appl { get; set; }
        public string exam_name { get; set; }
        public int appl_score { get; set; }
    }
}
